FROM golang:1.18 as modules

ADD go.mod go.sum /m/

RUN cd /m && go mod download

FROM golang:1.18 as builder

COPY --from=modules /go/pkg /go/pkg

RUN mkdir -p /src

ADD . /src

WORKDIR /src

RUN useradd -u 10001 process

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /app/process ./cmd/process

FROM busybox

EXPOSE 80

COPY --from=builder /etc/passwd /etc/passwd

USER process

WORKDIR /app

COPY --from=builder /app/process /app/process
COPY --from=builder /etc/ssl/certs/ /etc/ssl/certs/

CMD ["/app/process"]